package openai

import (
	"errors"
	"io"
	"net/http"
	"strings"

	"github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/dto"
	relaycommon "github.com/QuantumNous/new-api/relay/common"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/types"
	"github.com/gin-gonic/gin"
)

func GeminiImageChatCompatibilityHandler(c *gin.Context, info *relaycommon.RelayInfo, resp *http.Response) (*dto.Usage, *types.NewAPIError) {
	defer service.CloseResponseBodyGracefully(resp)

	responseBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, types.NewOpenAIError(err, types.ErrorCodeReadResponseBodyFailed, http.StatusInternalServerError)
	}

	openAIResponse, chatResponse, err := extractGeminiCompatibleImageResponse(responseBody)
	if err != nil {
		return nil, types.NewOpenAIError(err, types.ErrorCodeBadResponseBody, http.StatusInternalServerError)
	}
	if len(openAIResponse.Data) == 0 {
		return nil, types.NewOpenAIError(errors.New("no images generated by Gemini image API"), types.ErrorCodeEmptyResponse, http.StatusInternalServerError)
	}
	enforceImageResponseAspectRatio(info, &openAIResponse)

	jsonResponse, jsonErr := common.Marshal(openAIResponse)
	if jsonErr != nil {
		return nil, types.NewError(jsonErr, types.ErrorCodeBadResponseBody)
	}
	c.Writer.Header().Set("Content-Type", "application/json")
	c.Writer.WriteHeader(resp.StatusCode)
	_, _ = c.Writer.Write(jsonResponse)

	usage := service.ResponseText2Usage(c, "", info.UpstreamModelName, info.GetEstimatePromptTokens())
	if chatResponse.Usage.TotalTokens > 0 {
		usage = &chatResponse.Usage
	}
	if usage.CompletionTokens == 0 {
		usage.CompletionTokens = len(openAIResponse.Data) * 1400
		usage.TotalTokens = usage.PromptTokens + usage.CompletionTokens
	}
	service.RecordGeneratedImages(c, info, openAIResponse.Data, usage)
	return usage, nil
}

func extractGeminiCompatibleImageResponse(responseBody []byte) (dto.ImageResponse, dto.OpenAITextResponse, error) {
	var geminiResponse dto.GeminiChatResponse
	if err := common.Unmarshal(responseBody, &geminiResponse); err != nil {
		return dto.ImageResponse{}, dto.OpenAITextResponse{}, err
	}

	openAIResponse := dto.ImageResponse{
		Created: common.GetTimestamp(),
		Data:    make([]dto.ImageData, 0),
	}
	for _, candidate := range geminiResponse.Candidates {
		for _, part := range candidate.Content.Parts {
			if part.InlineData == nil || part.InlineData.Data == "" || !strings.HasPrefix(strings.ToLower(part.InlineData.MimeType), "image/") {
				continue
			}
			openAIResponse.Data = append(openAIResponse.Data, dto.ImageData{B64Json: part.InlineData.Data})
		}
	}

	if len(openAIResponse.Data) == 0 {
		var imageResponse dto.ImageResponse
		if err := common.Unmarshal(responseBody, &imageResponse); err == nil && len(imageResponse.Data) > 0 {
			for _, image := range imageResponse.Data {
				if image.B64Json == "" && image.Url == "" {
					continue
				}
				openAIResponse.Data = append(openAIResponse.Data, image)
			}
		}
	}

	var chatResponse dto.OpenAITextResponse
	if len(openAIResponse.Data) == 0 {
		if err := common.Unmarshal(responseBody, &chatResponse); err != nil {
			return dto.ImageResponse{}, dto.OpenAITextResponse{}, err
		}
		for _, choice := range chatResponse.Choices {
			for _, image := range choice.Message.Images {
				url := image.ImageUrl.Url
				if !strings.HasPrefix(strings.ToLower(url), "data:image/") {
					continue
				}
				openAIResponse.Data = append(openAIResponse.Data, dto.ImageData{B64Json: strings.TrimPrefix(url, "data:"+image.ImageUrl.MimeType+";base64,")})
				if strings.Contains(url, ";base64,") {
					openAIResponse.Data[len(openAIResponse.Data)-1].B64Json = url[strings.Index(url, ";base64,")+8:]
				}
			}
		}
	}
	return openAIResponse, chatResponse, nil
}
