package openai

import (
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/constant"
	"github.com/QuantumNous/new-api/dto"
	relaycommon "github.com/QuantumNous/new-api/relay/common"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/types"
	"github.com/gin-gonic/gin"
)

func GeminiImageChatCompatibilityHandler(c *gin.Context, info *relaycommon.RelayInfo, resp *http.Response) (*dto.Usage, *types.NewAPIError) {
	defer service.CloseResponseBodyGracefully(resp)

	responseBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, types.NewOpenAIError(err, types.ErrorCodeReadResponseBodyFailed, http.StatusInternalServerError)
	}

	var geminiResponse dto.GeminiChatResponse
	if err = common.Unmarshal(responseBody, &geminiResponse); err != nil {
		return nil, types.NewOpenAIError(err, types.ErrorCodeBadResponseBody, http.StatusInternalServerError)
	}

	openAIResponse := dto.ImageResponse{
		Created: common.GetTimestamp(),
		Data:    make([]dto.ImageData, 0),
	}

	if len(geminiResponse.Candidates) == 0 {
		openAIResponse.Data = collectOpenAIChatImages(responseBody)
		if len(openAIResponse.Data) > 0 {
			return writeGeminiImageCompatibilityResponse(c, info, resp, openAIResponse)
		}
		if geminiResponse.PromptFeedback != nil && geminiResponse.PromptFeedback.BlockReason != nil {
			common.SetContextKey(c, constant.ContextKeyAdminRejectReason, fmt.Sprintf("gemini_image_block_reason=%s", *geminiResponse.PromptFeedback.BlockReason))
			return nil, types.NewOpenAIError(errors.New("request blocked by Gemini image API: "+*geminiResponse.PromptFeedback.BlockReason), types.ErrorCodePromptBlocked, http.StatusBadRequest)
		}
		common.SetContextKey(c, constant.ContextKeyAdminRejectReason, "gemini_image_empty_candidates")
		return nil, types.NewOpenAIError(errors.New("empty response from Gemini image API"), types.ErrorCodeEmptyResponse, http.StatusInternalServerError)
	}

	for _, candidate := range geminiResponse.Candidates {
		for _, part := range candidate.Content.Parts {
			if part.InlineData == nil || part.InlineData.Data == "" || !strings.HasPrefix(strings.ToLower(part.InlineData.MimeType), "image/") {
				continue
			}
			openAIResponse.Data = append(openAIResponse.Data, dto.ImageData{B64Json: part.InlineData.Data})
		}
	}
	if len(openAIResponse.Data) == 0 {
		openAIResponse.Data = collectOpenAIChatImages(responseBody)
	}
	if len(openAIResponse.Data) == 0 {
		common.SetContextKey(c, constant.ContextKeyAdminRejectReason, geminiImageNoImageReason(&geminiResponse))
		return nil, types.NewOpenAIError(errors.New("no images generated by Gemini image API"), types.ErrorCodeEmptyResponse, http.StatusInternalServerError)
	}

	return writeGeminiImageCompatibilityResponse(c, info, resp, openAIResponse)
}

func writeGeminiImageCompatibilityResponse(c *gin.Context, info *relaycommon.RelayInfo, resp *http.Response, openAIResponse dto.ImageResponse) (*dto.Usage, *types.NewAPIError) {
	jsonResponse, jsonErr := common.Marshal(openAIResponse)
	if jsonErr != nil {
		return nil, types.NewError(jsonErr, types.ErrorCodeBadResponseBody)
	}
	c.Writer.Header().Set("Content-Type", "application/json")
	c.Writer.WriteHeader(resp.StatusCode)
	_, _ = c.Writer.Write(jsonResponse)

	usage := service.ResponseText2Usage(c, "", info.UpstreamModelName, info.GetEstimatePromptTokens())
	if usage.CompletionTokens == 0 {
		usage.CompletionTokens = len(openAIResponse.Data) * 1400
		usage.TotalTokens = usage.PromptTokens + usage.CompletionTokens
	}
	service.RecordGeneratedImages(c, info, openAIResponse.Data, usage)
	return usage, nil
}

func collectOpenAIChatImages(responseBody []byte) []dto.ImageData {
	var chatResponse dto.OpenAITextResponse
	if err := common.Unmarshal(responseBody, &chatResponse); err != nil {
		return nil
	}

	images := make([]dto.ImageData, 0)
	for _, choice := range chatResponse.Choices {
		for _, image := range choice.Message.Images {
			data := image.ImageUrl.Url
			if data == "" {
				continue
			}
			if strings.HasPrefix(data, "data:") {
				if commaIndex := strings.Index(data, ","); commaIndex >= 0 && commaIndex+1 < len(data) {
					data = data[commaIndex+1:]
				}
			}
			if data != "" {
				images = append(images, dto.ImageData{B64Json: data})
			}
		}
	}
	return images
}

func geminiImageNoImageReason(response *dto.GeminiChatResponse) string {
	if response == nil {
		return "gemini_image_no_inline_image"
	}

	reasons := make([]string, 0, len(response.Candidates))
	for _, candidate := range response.Candidates {
		if candidate.FinishReason != nil && *candidate.FinishReason != "" {
			reasons = append(reasons, *candidate.FinishReason)
		}
	}
	if len(reasons) == 0 {
		return "gemini_image_no_inline_image"
	}
	return "gemini_image_no_inline_image_finish_reason=" + strings.Join(reasons, ",")
}
